### PR TITLE
Make parser deduce decimal mark when there is only one delimiter in a string and major is 0

### PR DESCRIPTION
**Pull request by trushkevich**

### CODE REVIEW

**Review by antstorm — CHANGES_REQUESTED** [review]
This is a great improvement, thank you! 👍 

It's probably worth putting this into at least `1.11` because the change is potentially breaking, however I don't expect anyone depending on the legacy behaviour

**Comment by trushkevich** [comment]
Ok, I updated version in the changelog

**Comment by semmons99** [comment]
@trushkevich you need to update lib/monetize/version.rb too, then we are good to go

**Comment by trushkevich** [comment]
@semmons99 ok, done

**Review by semmons99 — APPROVED** [review]

**Comment by semmons99** [comment]
released

**Pull request merged**
