### PR TITLE
Current money-rails to_hash is different. Updating to_money to match.

### PR DESCRIPTION
**Pull request by nitsujri**
Request for changes are welcome!

### CODE REVIEW

**Review by heangpov16 — COMMENTED** [review]
[Support Money all ](https://twitter.com/HeangPov2?s=09)

**Review by heangpov16 — APPROVED** [review]
[Khmer](https://twitter.com/HeangPov2?s=09)

**Review by semmons99 — APPROVED** [review]

**Comment by nitsujri** [comment]
@semmons99 great thanks for the review! is there anything I can do to help get the tests to run and merged?

**Comment by semmons99** [comment]
merged and released as 1.12.0

**Pull request merged**
