### PR TITLE
Added Swedish krona support

### PR DESCRIPTION
**Pull request by umate**

### CODE REVIEW

**Comment by antstorm** [comment]
@umate thank you for the commit, I'll merge it, but will refactor how symbols are parsed and tested, otherwise this violates DRY

**Comment by umate** [comment]
thank you @antstorm

**Comment by ct-clearhaus** [comment]
I respectfully disagree and made #71 :smiley:

**Comment by antstorm** [comment]
@ct-clearhaus thank you!

**Pull request merged**
