### PR TITLE
Update travis list and add jruby

### PR DESCRIPTION
**Pull request by spk**
Update travis list
Cheers

### CODE REVIEW

**Comment by bensheldon** [comment]
A larger build matrix will add some time to run the tests; seems like a change from 1min to 14min.

Also, the jruby build is both failing and ignored. It seems to be failing on installing rspec 3.0

**Comment by spk** [comment]
Hi @bensheldon, I've updated the PR with your suggestions.
I guess the coverage error is normal ?

**Comment by antstorm** [comment]
@spk can you please rebase it with `master`?

**Comment by spk** [comment]
@antstorm updated

**Comment by antstorm** [comment]
@spk great, thank you! Merging!

**Pull request merged**
