### PR TITLE
Parse currency amounts given with suffixes

### PR DESCRIPTION
**Pull request by aredondo**
This change allows Monetize to parse currency amounts with suffixes such as €126.36M, or -$2.45B. Four suffixes are recognized: K, M, B, and T. They can be given in lower or upper case, but must directly follow the number to be interpreted as a multiplier suffix.

Both previous and new tests pass correctly. Are there maybe other corner cases that should be considered?

There is pending the matter of scale. For now, the billion and trillion suffixes are assumed to be given in short scale—that is, 10<sup>9</sup> and 10<sup>12</sup>, respectively. This is probably the most common case for currencies. Still, it may be worth it to consider the possibility of having a configuration flag so that long scale can be selected.

### CODE REVIEW

**Comment by semmons99** [comment]
looks good to me, just update the changelog and let me know when you do

**Comment by aredondo** [comment]
I am happy that you find the change useful.

How do you want me to update the changelog? Am I to add a new version? The text I would add is something like:

    Add capability to parse currency amounts given with suffixes (K, M, B, and T)

**Comment by semmons99** [comment]
Just place it under the master heading for now

**Comment by aredondo** [comment]
Ok, it's done.

**Pull request merged**
